// Code generated by "stringer -type GameStat"; DO NOT EDIT

package main

import "fmt"

const (
	_GameStat_name_0 = "INIT"
	_GameStat_name_1 = "RUN"
	_GameStat_name_2 = "PAUSE"
	_GameStat_name_3 = "GAME_OVER"
)

var (
	_GameStat_index_0 = [...]uint8{0, 4}
	_GameStat_index_1 = [...]uint8{0, 3}
	_GameStat_index_2 = [...]uint8{0, 5}
	_GameStat_index_3 = [...]uint8{0, 9}
)

func (i GameStat) String() string {
	switch {
	case i == 0:
		return _GameStat_name_0
	case i == 2:
		return _GameStat_name_1
	case i == 4:
		return _GameStat_name_2
	case i == 8:
		return _GameStat_name_3
	default:
		return fmt.Sprintf("GameStat(%d)", i)
	}
}
