// Code generated by "stringer -type State"; DO NOT EDIT

package main

import "fmt"

const (
	_State_name_0 = "INIT"
	_State_name_1 = "RUN"
	_State_name_2 = "PAUSE"
	_State_name_3 = "GAME_OVER"
)

var (
	_State_index_0 = [...]uint8{0, 4}
	_State_index_1 = [...]uint8{0, 3}
	_State_index_2 = [...]uint8{0, 5}
	_State_index_3 = [...]uint8{0, 9}
)

func (i State) String() string {
	switch {
	case i == 0:
		return _State_name_0
	case i == 2:
		return _State_name_1
	case i == 4:
		return _State_name_2
	case i == 8:
		return _State_name_3
	default:
		return fmt.Sprintf("State(%d)", i)
	}
}
